services:

  react-frontend:
    image: node:latest

    working_dir: /app
    
    volumes:
      - ../:/app
    
    ports:
      - "80:5173"
    
    command: sh -c "npm install && npm run dev -- --host"

  socket-server:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    
    working_dir: /app
    
    volumes:
      - ../server:/app
    
    ports:
      - "8080:8080"

    command: sh -c "dotnet watch run"